USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS TALABAT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS TALABAT;
CREATE SCHEMA  IF NOT EXISTS TALABAT.BRONZE;    
CREATE SCHEMA  IF NOT EXISTS TALABAT.RAW;      
CREATE SCHEMA  IF NOT EXISTS TALABAT.STAGING;  
CREATE SCHEMA  IF NOT EXISTS TALABAT.MARTS;    
CREATE SCHEMA  IF NOT EXISTS TALABAT.SNAPSHOTS; 
CREATE SCHEMA  IF NOT EXISTS TALABAT.AI;        

CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE   ON WAREHOUSE TALABAT_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE TALABAT_WH TO ROLE DBT_ROLE;
GRANT ALL     ON DATABASE  TALABAT    TO ROLE DBT_ROLE;
GRANT ALL     ON ALL SCHEMAS IN DATABASE TALABAT TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE SCHEMAS IN DATABASE TALABAT TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE TABLES IN DATABASE TALABAT TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE VIEWS  IN DATABASE TALABAT TO ROLE DBT_ROLE;
GRANT ROLE DBT_ROLE TO USER "3BTAWAB1";

SELECT 'setup complete' AS status;
