USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION TALABAT_BLOB_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = '*******************************'
  STORAGE_ALLOWED_LOCATIONS = ('**********************************');

GRANT USAGE ON INTEGRATION TALABAT_BLOB_INT TO ROLE DBT_ROLE;

DESC INTEGRATION TALABAT_BLOB_INT;
