CREATE OR REPLACE FILE FORMAT TALABAT.RAW.CSV_FMT
  TYPE = 'CSV'
  COMPRESSION = 'AUTO'                 
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1                          
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', '\\N', 'NULL')
  TRIM_SPACE = FALSE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE; 

CREATE OR REPLACE STAGE TALABAT.RAW.TALABAT_STAGE
  STORAGE_INTEGRATION = TALABAT_BLOB_INT
  URL = '**********************************************'
  FILE_FORMAT = TALABAT.RAW.CSV_FMT;

LIST @TALABAT.RAW.TALABAT_STAGE
