USE ROLE ACCOUNTADMIN;
USE DATABASE TALABAT;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE TALABAT.RAW.OLIST_CUSTOMER_DATASET (
    CUSTOMER_ID              VARCHAR,
    CUSTOMER_UNIQUE_ID       VARCHAR,
    CUSTOMER_ZIP_CODE_PREFIX VARCHAR,
    CUSTOMER_CITY            VARCHAR,
    CUSTOMER_STATE           VARCHAR
);

CREATE OR REPLACE TABLE TALABAT.RAW.OLIST_GEOLOCATION_DATASET (
    GEOLOCATION_ZIP_CODE_PREFIX VARCHAR,
    GEOLOCATION_LAT             FLOAT,
    GEOLOCATION_LNG             FLOAT,
    GEOLOCATION_CITY            VARCHAR,
    GEOLOCATION_STATE           VARCHAR
);

CREATE OR REPLACE TABLE TALABAT.RAW.OLIST_ORDER_ITEMS_DATASET (
    ORDER_ID             VARCHAR,
    ORDER_ITEM_ID        INT,
    PRODUCT_ID           VARCHAR,
    SELLER_ID            VARCHAR,
    SHIPPING_LIMIT_DATE  TIMESTAMP,
    PRICE                FLOAT,
    FREIGHT_VALUE        FLOAT
);

CREATE OR REPLACE TABLE TALABAT.RAW.OLIST_ORDER_PAYMENTS_DATASET (
    ORDER_ID              VARCHAR,
    PAYMENT_SEQUENTIAL    INT,
    PAYMENT_TYPE          VARCHAR,
    PAYMENT_INSTALLMENTS  INT,
    PAYMENT_VALUE         FLOAT
);

CREATE OR REPLACE TABLE TALABAT.RAW.OLIST_ORDER_REVIEWS_DATASET (
    REVIEW_ID                VARCHAR,
    ORDER_ID                 VARCHAR,
    REVIEW_SCORE             INT,
    REVIEW_COMMENT_TITLE     VARCHAR,
    REVIEW_COMMENT_MESSAGE   VARCHAR,
    REVIEW_CREATION_DATE     TIMESTAMP,
    REVIEW_ANSWER_TIMESTAMP  TIMESTAMP
);

CREATE OR REPLACE TABLE TALABAT.RAW.OLIST_ORDERS_DATASET (
    ORDER_ID                      VARCHAR,
    CUSTOMER_ID                   VARCHAR,
    ORDER_STATUS                  VARCHAR,
    ORDER_PURCHASE_TIMESTAMP      TIMESTAMP,
    ORDER_APPROVED_AT             TIMESTAMP,
    ORDER_DELIVERED_CARRIER_DATE  TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE TALABAT.RAW.OLIST_PRODUCTS_DATASET (
    PRODUCT_ID                 VARCHAR,
    PRODUCT_CATEGORY_NAME      VARCHAR,
    PRODUCT_NAME_LENGTH        INT,
    PRODUCT_DESCRIPTION_LENGTH INT,
    PRODUCT_PHOTOS_QTY         INT,
    PRODUCT_WEIGHT_G           INT,
    PRODUCT_LENGTH_CM          INT,
    PRODUCT_HEIGHT_CM          INT,
    PRODUCT_WIDTH_CM           INT
);

CREATE OR REPLACE TABLE TALABAT.RAW.OLIST_SELLERS_DATASET (
    SELLER_ID              VARCHAR,
    SELLER_ZIP_CODE_PREFIX VARCHAR,
    SELLER_CITY            VARCHAR,
    SELLER_STATE           VARCHAR
);
