USE ROLE ACCOUNTADMIN;
USE DATABASE TALABAT;
USE SCHEMA RAW;
USE WAREHOUSE TALABAT_WH;

COPY INTO OLIST_CUSTOMER_DATASET
FROM @TALABAT_STAGE/olist_customers_dataset.csv
FILE_FORMAT = CSV_FMT
ON_ERROR = 'CONTINUE';

COPY INTO OLIST_GEOLOCATION_DATASET
FROM @TALABAT_STAGE/olist_geolocation_dataset.csv
FILE_FORMAT = CSV_FMT
ON_ERROR = 'CONTINUE';

COPY INTO OLIST_ORDER_ITEMS_DATASET
FROM @TALABAT_STAGE/olist_order_items_dataset.csv
FILE_FORMAT = CSV_FMT
ON_ERROR = 'CONTINUE';

COPY INTO OLIST_ORDER_PAYMENTS_DATASET
FROM @TALABAT_STAGE/olist_order_payments_dataset.csv
FILE_FORMAT = CSV_FMT
ON_ERROR = 'CONTINUE';

COPY INTO OLIST_ORDER_REVIEWS_DATASET
FROM @TALABAT_STAGE/olist_order_reviews_dataset.csv
FILE_FORMAT = CSV_FMT
ON_ERROR = 'CONTINUE';

COPY INTO OLIST_ORDERS_DATASET
FROM @TALABAT_STAGE/olist_orders_dataset.csv
FILE_FORMAT = CSV_FMT
ON_ERROR = 'CONTINUE';

COPY INTO OLIST_PRODUCTS_DATASET
FROM @TALABAT_STAGE/olist_products_dataset.csv
FILE_FORMAT = CSV_FMT
ON_ERROR = 'CONTINUE';

COPY INTO OLIST_SELLERS_DATASET
FROM @TALABAT_STAGE/olist_sellers_dataset.csv
FILE_FORMAT = CSV_FMT
ON_ERROR = 'CONTINUE';
