FROM apache/airflow:3.0.5-python3.12

RUN pip install --no-cache-dir \
      "apache-airflow-providers-snowflake>=6.5.0" \
      apache-airflow-providers-fab 

RUN python -m venv /opt/airflow/dbt_venv && \
    /opt/airflow/dbt_venv/bin/pip install --no-cache-dir "dbt-snowflake==1.8.*"
